# User Configuration
# All driver Kconfig is in Kconfig.defconfig

CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000

CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
# consumer report basic to be compatible with nintendo switch
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y
